name: hello-systemtag-snap
version: '1.0'
summary: GNU Hello, the "hello world systemtag" snap
description: GNU hello prints a friendly greeting.
grade: stable
confinement: strict

apps:
  hello:
    command: bin/hello

parts:
  gnu-hello:
    source: ./hello/
    plugin: autotools
